### ISSUE TITLE
LongPullErr

### ISSUE THREAD

**Issue by wgliyuli** [xiaojiaoyu100/aliyun-acm#4]
#### 场景描述
1. 一个项目内，拥有多个轮询获取ACM配置的时，错误打印定位不了
2. 使用SetHook()时，会重复打印一遍错误。

#### 建议
1. LongPullErr打印日志时，添加Group和DataID
``` golang
log.Printf("[Error](%s %s)LongPullErr：%s",unit.Group, unit.DataID, err.Error())
```
2. 使用SetHook()打印日志时，LongPullErr不再打印错误日志，

**Comment by zenghur** [comment]
v2.0.6修改成为不打印。由用户提供函数自行打印。
